"""Add Trade History models

Revision ID: c5eed52a3180
Revises: bf8b147f0359
Create Date: 2024-11-18 01:46:44.452449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5eed52a3180"
down_revision: Union[str, None] = "bf8b147f0359"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trade_history", "buyer_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "trade_history",
        "seller_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trade_history", "seller_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "trade_history", "buyer_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
