"""Add Token, UserAsset models

Revision ID: aa50eb99459e
Revises: 639e2d8d0912
Create Date: 2024-11-16 22:04:53.745580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa50eb99459e"
down_revision: Union[str, None] = "639e2d8d0912"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
