"""Add new models

Revision ID: c8f188692eae
Revises: c5eed52a3180
Create Date: 2024-11-18 02:02:40.688477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8f188692eae"
down_revision: Union[str, None] = "c5eed52a3180"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("pair", sa.String(), nullable=False))
    op.alter_column(
        "orders",
        "price",
        existing_type=sa.NUMERIC(precision=32, scale=8),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "amount",
        existing_type=sa.NUMERIC(precision=32, scale=8),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "remaining_amount",
        existing_type=sa.NUMERIC(precision=32, scale=8),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_constraint(
        "fk_orders_token_id_tokens", "orders", type_="foreignkey"
    )
    op.drop_column("orders", "token_id")
    op.add_column(
        "trade_history", sa.Column("pair", sa.String(), nullable=False)
    )
    op.alter_column(
        "trade_history",
        "price",
        existing_type=sa.NUMERIC(precision=32, scale=8),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "trade_history",
        "amount",
        existing_type=sa.NUMERIC(precision=32, scale=8),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trade_history",
        "amount",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=32, scale=8),
        existing_nullable=False,
    )
    op.alter_column(
        "trade_history",
        "price",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=32, scale=8),
        existing_nullable=False,
    )
    op.drop_column("trade_history", "pair")
    op.add_column(
        "orders",
        sa.Column(
            "token_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_orders_token_id_tokens", "orders", "tokens", ["token_id"], ["id"]
    )
    op.alter_column(
        "orders",
        "remaining_amount",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=32, scale=8),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "amount",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=32, scale=8),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "price",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=32, scale=8),
        existing_nullable=False,
    )
    op.drop_column("orders", "pair")
    # ### end Alembic commands ###
