"""Add Token, UserAsset models

Revision ID: 20ed6dfa5f89
Revises: aa50eb99459e
Create Date: 2024-11-16 22:28:35.023904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20ed6dfa5f89"
down_revision: Union[str, None] = "aa50eb99459e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
